import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import local from 'next/font/local'
import HeaderItem from '@/components/common/header'
import FooterItem from '@/components/common/footer'
import './globals.css'

const PoppinsFont = Poppins({
    preload: true,
    weight: '400',
})
export const metadata: Metadata = {
    title: 'Street7',
    description: 'Generated by create next app',
};

const CasterFont = local({
    src: "./fonts/Caster.ttf",
    preload : true,
    weight : "400"
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${CasterFont.className} antialiased`}>
                <div className="min-h-screen w-full max-w-[1440px] mx-auto">
                    <HeaderItem />
                    <div className="w-[calc(100%-2rem)] sm:w-[calc(100%-3rem)] md:w-[calc(100%-4rem)] lg:w-[calc(100%-6rem)] xl:w-[calc(100%-8rem)] mx-auto">
                        {children}
                    </div>
                    <FooterItem />
                </div>
            </body>
        </html>
    )
}