import type { Metadata } from 'next'
import local from 'next/font/local'
import HeaderItem from '@/components/common/header'
import FooterItem from '@/components/common/footer'
import './globals.css'
import SiteMain from '@/components/common/site.main'


export const metadata: Metadata = {
    title: 'Street7',
    description: 'Generated by create next app',
};

const Ragiften  = local({
    src : "./fonts/Ragiften-G3OlO.otf",
    variable : "--ragfont",
    weight:"300"
})

const NeueMontreal = local( {
    src : "./fonts/NeueMontreal-Regular.otf",
    preload  : true,
})
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${NeueMontreal.className} ${Ragiften.variable} antialiased`}>
               <SiteMain>
                    <div>{children}</div>
               </SiteMain>
            </body>
        </html>
    )
}
