import type { Metadata } from 'next'
import local from 'next/font/local'
import HeaderItem from '@/components/common/header'
import FooterItem from '@/components/common/footer'
import './globals.css'


export const metadata: Metadata = {
    title: 'Street7',
    description: 'Generated by create next app',
};

const Ragiften  = local({
    src : "./fonts/Ragiften-G3OlO.otf",
    variable : "--ragfont",
    weight:"300"
})

const NeueMontreal = local( {
    src : "./fonts/NeueMontreal-Regular.otf",
    preload  : true,
})
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${NeueMontreal.className} ${Ragiften.variable} antialiased`}>
                <div className="min-h-screen w-full max-w-[1440px] mx-auto">
                    <HeaderItem />
                    <div className="w-[calc(100%-2rem)] sm:w-[calc(100%-3rem)] md:w-[calc(100%-4rem)] lg:w-[calc(100%-6rem)] xl:w-[calc(100%-8rem)] mx-auto">
                        {children}
                    </div>
                    <FooterItem />
                </div>
            </body>
        </html>
    )
}